"""add a profile pic path section

Revision ID: 00227e581615
Revises: a5fb19e7309a
Create Date: 2021-09-18 16:36:38.145807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00227e581615'
down_revision = 'a5fb19e7309a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
