"""remove the title category

Revision ID: 73956c8cad0f
Revises: 691f3d6fe7d7
Create Date: 2021-09-18 20:07:15.996014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73956c8cad0f'
down_revision = '691f3d6fe7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_category', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'pitch_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch_category')
    # ### end Alembic commands ###
