"""add an upvote and a downvote column

Revision ID: a3ad15ae1994
Revises: aca712f7f5dc
Create Date: 2021-09-20 19:01:39.434548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ad15ae1994'
down_revision = 'aca712f7f5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('upvote', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('downvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'downvote')
    op.drop_column('comments', 'upvote')
    # ### end Alembic commands ###
